server {
    listen 443 ssl;
    server_name perfactchat.com;

    ssl_certificate /etc/letsencrypt/live/perfactchat.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/perfactchat.com/privkey.pem;

    location / {
        proxy_pass http://localhost:6000;  # Make sure it's using http if Node.js is not on HTTPS
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

